// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/anchor.proto

package com.medlinker.protocol.message.types;

public final class AnchorOuterClass {
  private AnchorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnchorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.types.Anchor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string href = 1;</code>
     */
    String getHref();
    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string href = 1;</code>
     */
    com.google.protobuf.ByteString
        getHrefBytes();

    /**
     * <pre>
     * 需要做超链接文本起始下标
     * </pre>
     *
     * <code>int32 start = 2;</code>
     */
    int getStart();

    /**
     * <pre>
     * 超链接文本字符(非字节)长度
     * </pre>
     *
     * <code>int32 len = 3;</code>
     */
    int getLen();
  }
  /**
   * Protobuf type {@code com.medlinker.protocol.message.types.Anchor}
   */
  public  static final class Anchor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.types.Anchor)
      AnchorOrBuilder {
    // Use Anchor.newBuilder() to construct.
    private Anchor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Anchor() {
      href_ = "";
      start_ = 0;
      len_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Anchor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              href_ = s;
              break;
            }
            case 16: {

              start_ = input.readInt32();
              break;
            }
            case 24: {

              len_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnchorOuterClass.internal_static_protocol_message_types_Anchor_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnchorOuterClass.internal_static_protocol_message_types_Anchor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Anchor.class, Builder.class);
    }

    public static final int HREF_FIELD_NUMBER = 1;
    private volatile Object href_;
    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string href = 1;</code>
     */
    public String getHref() {
      Object ref = href_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        href_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string href = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHrefBytes() {
      Object ref = href_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        href_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 2;
    private int start_;
    /**
     * <pre>
     * 需要做超链接文本起始下标
     * </pre>
     *
     * <code>int32 start = 2;</code>
     */
    public int getStart() {
      return start_;
    }

    public static final int LEN_FIELD_NUMBER = 3;
    private int len_;
    /**
     * <pre>
     * 超链接文本字符(非字节)长度
     * </pre>
     *
     * <code>int32 len = 3;</code>
     */
    public int getLen() {
      return len_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHrefBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, href_);
      }
      if (start_ != 0) {
        output.writeInt32(2, start_);
      }
      if (len_ != 0) {
        output.writeInt32(3, len_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHrefBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, href_);
      }
      if (start_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, start_);
      }
      if (len_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, len_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Anchor)) {
        return super.equals(obj);
      }
      Anchor other = (Anchor) obj;

      boolean result = true;
      result = result && getHref()
          .equals(other.getHref());
      result = result && (getStart()
          == other.getStart());
      result = result && (getLen()
          == other.getLen());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HREF_FIELD_NUMBER;
      hash = (53 * hash) + getHref().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart();
      hash = (37 * hash) + LEN_FIELD_NUMBER;
      hash = (53 * hash) + getLen();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Anchor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Anchor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Anchor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Anchor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Anchor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Anchor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Anchor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Anchor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Anchor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Anchor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Anchor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.medlinker.protocol.message.types.Anchor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.types.Anchor)
        AnchorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnchorOuterClass.internal_static_protocol_message_types_Anchor_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnchorOuterClass.internal_static_protocol_message_types_Anchor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Anchor.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.types.AnchorOuterClass.Anchor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        href_ = "";

        start_ = 0;

        len_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnchorOuterClass.internal_static_protocol_message_types_Anchor_descriptor;
      }

      public Anchor getDefaultInstanceForType() {
        return Anchor.getDefaultInstance();
      }

      public Anchor build() {
        Anchor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Anchor buildPartial() {
        Anchor result = new Anchor(this);
        result.href_ = href_;
        result.start_ = start_;
        result.len_ = len_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Anchor) {
          return mergeFrom((Anchor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Anchor other) {
        if (other == Anchor.getDefaultInstance()) return this;
        if (!other.getHref().isEmpty()) {
          href_ = other.href_;
          onChanged();
        }
        if (other.getStart() != 0) {
          setStart(other.getStart());
        }
        if (other.getLen() != 0) {
          setLen(other.getLen());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Anchor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Anchor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object href_ = "";
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string href = 1;</code>
       */
      public String getHref() {
        Object ref = href_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          href_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string href = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHrefBytes() {
        Object ref = href_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          href_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string href = 1;</code>
       */
      public Builder setHref(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        href_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string href = 1;</code>
       */
      public Builder clearHref() {
        
        href_ = getDefaultInstance().getHref();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string href = 1;</code>
       */
      public Builder setHrefBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        href_ = value;
        onChanged();
        return this;
      }

      private int start_ ;
      /**
       * <pre>
       * 需要做超链接文本起始下标
       * </pre>
       *
       * <code>int32 start = 2;</code>
       */
      public int getStart() {
        return start_;
      }
      /**
       * <pre>
       * 需要做超链接文本起始下标
       * </pre>
       *
       * <code>int32 start = 2;</code>
       */
      public Builder setStart(int value) {
        
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要做超链接文本起始下标
       * </pre>
       *
       * <code>int32 start = 2;</code>
       */
      public Builder clearStart() {
        
        start_ = 0;
        onChanged();
        return this;
      }

      private int len_ ;
      /**
       * <pre>
       * 超链接文本字符(非字节)长度
       * </pre>
       *
       * <code>int32 len = 3;</code>
       */
      public int getLen() {
        return len_;
      }
      /**
       * <pre>
       * 超链接文本字符(非字节)长度
       * </pre>
       *
       * <code>int32 len = 3;</code>
       */
      public Builder setLen(int value) {
        
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 超链接文本字符(非字节)长度
       * </pre>
       *
       * <code>int32 len = 3;</code>
       */
      public Builder clearLen() {
        
        len_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.types.Anchor)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.types.Anchor)
    private static final Anchor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Anchor();
    }

    public static Anchor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Anchor>
        PARSER = new com.google.protobuf.AbstractParser<Anchor>() {
      public Anchor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Anchor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Anchor> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Anchor> getParserForType() {
      return PARSER;
    }

    public Anchor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_types_Anchor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_types_Anchor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022types/anchor.proto\022\026protocol.message.t" +
      "ypes\"2\n\006Anchor\022\014\n\004href\030\001 \001(\t\022\r\n\005start\030\002 " +
      "\001(\005\022\013\n\003len\030\003 \001(\005BD\n$com.medlinker.protoc" +
      "ol.message.typesZ\034grape/protocol/message" +
      "/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_message_types_Anchor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_types_Anchor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_types_Anchor_descriptor,
        new String[] { "Href", "Start", "Len", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
