// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/business_card.proto

package com.medlinker.protocol.message.types;

public final class BusinessCardOuterClass {
  private BusinessCardOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BusinessCardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.types.BusinessCard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户
     * </pre>
     *
     * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
     */
    boolean hasUser();
    /**
     * <pre>
     *用户
     * </pre>
     *
     * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
     */
    com.medlinker.protocol.message.misc.UserOuterClass.User getUser();
    /**
     * <pre>
     *用户
     * </pre>
     *
     * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
     */
    com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getUserOrBuilder();
  }
  /**
   * <pre>
   * 名片
   * </pre>
   *
   * Protobuf type {@code com.medlinker.protocol.message.types.BusinessCard}
   */
  public  static final class BusinessCard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.types.BusinessCard)
      BusinessCardOrBuilder {
    // Use BusinessCard.newBuilder() to construct.
    private BusinessCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BusinessCard() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BusinessCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.medlinker.protocol.message.misc.UserOuterClass.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.medlinker.protocol.message.misc.UserOuterClass.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BusinessCardOuterClass.internal_static_protocol_message_types_BusinessCard_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BusinessCardOuterClass.internal_static_protocol_message_types_BusinessCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BusinessCard.class, Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private com.medlinker.protocol.message.misc.UserOuterClass.User user_;
    /**
     * <pre>
     *用户
     * </pre>
     *
     * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <pre>
     *用户
     * </pre>
     *
     * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
     */
    public com.medlinker.protocol.message.misc.UserOuterClass.User getUser() {
      return user_ == null ? com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance() : user_;
    }
    /**
     * <pre>
     *用户
     * </pre>
     *
     * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
     */
    public com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BusinessCard)) {
        return super.equals(obj);
      }
      BusinessCard other = (BusinessCard) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BusinessCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BusinessCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BusinessCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BusinessCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BusinessCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BusinessCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BusinessCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BusinessCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BusinessCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BusinessCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BusinessCard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 名片
     * </pre>
     *
     * Protobuf type {@code com.medlinker.protocol.message.types.BusinessCard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.types.BusinessCard)
        BusinessCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BusinessCardOuterClass.internal_static_protocol_message_types_BusinessCard_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BusinessCardOuterClass.internal_static_protocol_message_types_BusinessCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BusinessCard.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.types.BusinessCardOuterClass.BusinessCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BusinessCardOuterClass.internal_static_protocol_message_types_BusinessCard_descriptor;
      }

      public BusinessCard getDefaultInstanceForType() {
        return BusinessCard.getDefaultInstance();
      }

      public BusinessCard build() {
        BusinessCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BusinessCard buildPartial() {
        BusinessCard result = new BusinessCard(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BusinessCard) {
          return mergeFrom((BusinessCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BusinessCard other) {
        if (other == BusinessCard.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BusinessCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BusinessCard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.medlinker.protocol.message.misc.UserOuterClass.User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> userBuilder_;
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public Builder setUser(com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public Builder setUser(
          com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public Builder mergeUser(com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.medlinker.protocol.message.misc.UserOuterClass.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <pre>
       *用户
       * </pre>
       *
       * <code>.com.medlinker.protocol.message.misc.User user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.types.BusinessCard)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.types.BusinessCard)
    private static final BusinessCard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BusinessCard();
    }

    public static BusinessCard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BusinessCard>
        PARSER = new com.google.protobuf.AbstractParser<BusinessCard>() {
      public BusinessCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BusinessCard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BusinessCard> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BusinessCard> getParserForType() {
      return PARSER;
    }

    public BusinessCard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_types_BusinessCard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_types_BusinessCard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031types/business_card.proto\022\026protocol.me" +
      "ssage.types\032\017misc/user.proto\"9\n\014Business" +
      "Card\022)\n\004user\030\001 \001(\0132\033.com.medlinker.protocol.message.mi" +
      "sc.UserBD\n$com.medlinker.protocol.messag" +
      "e.typesZ\034grape/protocol/message/typesb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.medlinker.protocol.message.misc.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protocol_message_types_BusinessCard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_types_BusinessCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_types_BusinessCard_descriptor,
        new String[] { "User", });
    com.medlinker.protocol.message.misc.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
