// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/card.proto

package com.medlinker.protocol.message.types;

public final class CardOuterClass {
  private CardOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.types.Card)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 卡片类型 由native约定
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 2;</code>
     */
    String getLabel();
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    String getTitle();
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * 副标题
     * </pre>
     *
     * <code>string subtitle = 4;</code>
     */
    String getSubtitle();
    /**
     * <pre>
     * 副标题
     * </pre>
     *
     * <code>string subtitle = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubtitleBytes();

    /**
     * <pre>
     * 摘要
     * </pre>
     *
     * <code>string summary = 5;</code>
     */
    String getSummary();
    /**
     * <pre>
     * 摘要
     * </pre>
     *
     * <code>string summary = 5;</code>
     */
    com.google.protobuf.ByteString
        getSummaryBytes();

    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>string image = 6;</code>
     */
    String getImage();
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>string image = 6;</code>
     */
    com.google.protobuf.ByteString
        getImageBytes();

    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string url = 7;</code>
     */
    String getUrl();
    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string url = 7;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     * 显示位置 0:系统消息会话; 1:toast only; 2:会话+toast
     * </pre>
     *
     * <code>int32 display = 8;</code>
     */
    int getDisplay();

    /**
     * <pre>
     * card 特定type的额外信息
     * </pre>
     *
     * <code>string extra = 9;</code>
     */
    String getExtra();
    /**
     * <pre>
     * card 特定type的额外信息
     * </pre>
     *
     * <code>string extra = 9;</code>
     */
    com.google.protobuf.ByteString
        getExtraBytes();
  }
  /**
   * Protobuf type {@code com.medlinker.protocol.message.types.Card}
   */
  public  static final class Card extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.types.Card)
      CardOrBuilder {
    // Use Card.newBuilder() to construct.
    private Card(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Card() {
      type_ = 0;
      label_ = "";
      title_ = "";
      subtitle_ = "";
      summary_ = "";
      image_ = "";
      url_ = "";
      display_ = 0;
      extra_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Card(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              subtitle_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              summary_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              image_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 64: {

              display_ = input.readInt32();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CardOuterClass.internal_static_protocol_message_types_Card_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CardOuterClass.internal_static_protocol_message_types_Card_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Card.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 卡片类型 由native约定
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile Object label_;
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 2;</code>
     */
    public String getLabel() {
      Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private volatile Object title_;
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBTITLE_FIELD_NUMBER = 4;
    private volatile Object subtitle_;
    /**
     * <pre>
     * 副标题
     * </pre>
     *
     * <code>string subtitle = 4;</code>
     */
    public String getSubtitle() {
      Object ref = subtitle_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subtitle_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 副标题
     * </pre>
     *
     * <code>string subtitle = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubtitleBytes() {
      Object ref = subtitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subtitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUMMARY_FIELD_NUMBER = 5;
    private volatile Object summary_;
    /**
     * <pre>
     * 摘要
     * </pre>
     *
     * <code>string summary = 5;</code>
     */
    public String getSummary() {
      Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 摘要
     * </pre>
     *
     * <code>string summary = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_FIELD_NUMBER = 6;
    private volatile Object image_;
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>string image = 6;</code>
     */
    public String getImage() {
      Object ref = image_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        image_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>string image = 6;</code>
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 7;
    private volatile Object url_;
    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string url = 7;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 链接
     * </pre>
     *
     * <code>string url = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAY_FIELD_NUMBER = 8;
    private int display_;
    /**
     * <pre>
     * 显示位置 0:系统消息会话; 1:toast only; 2:会话+toast
     * </pre>
     *
     * <code>int32 display = 8;</code>
     */
    public int getDisplay() {
      return display_;
    }

    public static final int EXTRA_FIELD_NUMBER = 9;
    private volatile Object extra_;
    /**
     * <pre>
     * card 特定type的额外信息
     * </pre>
     *
     * <code>string extra = 9;</code>
     */
    public String getExtra() {
      Object ref = extra_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * card 特定type的额外信息
     * </pre>
     *
     * <code>string extra = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
      }
      if (!getSubtitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, subtitle_);
      }
      if (!getSummaryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, summary_);
      }
      if (!getImageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, image_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, url_);
      }
      if (display_ != 0) {
        output.writeInt32(8, display_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, extra_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
      }
      if (!getSubtitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, subtitle_);
      }
      if (!getSummaryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, summary_);
      }
      if (!getImageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, image_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, url_);
      }
      if (display_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, display_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, extra_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Card)) {
        return super.equals(obj);
      }
      Card other = (Card) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getLabel()
          .equals(other.getLabel());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getSubtitle()
          .equals(other.getSubtitle());
      result = result && getSummary()
          .equals(other.getSummary());
      result = result && getImage()
          .equals(other.getImage());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && (getDisplay()
          == other.getDisplay());
      result = result && getExtra()
          .equals(other.getExtra());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + SUBTITLE_FIELD_NUMBER;
      hash = (53 * hash) + getSubtitle().hashCode();
      hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSummary().hashCode();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + DISPLAY_FIELD_NUMBER;
      hash = (53 * hash) + getDisplay();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Card parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Card parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Card parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Card parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Card parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Card parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Card parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Card parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Card parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Card parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Card prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.medlinker.protocol.message.types.Card}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.types.Card)
        CardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CardOuterClass.internal_static_protocol_message_types_Card_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CardOuterClass.internal_static_protocol_message_types_Card_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Card.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.types.CardOuterClass.Card.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        label_ = "";

        title_ = "";

        subtitle_ = "";

        summary_ = "";

        image_ = "";

        url_ = "";

        display_ = 0;

        extra_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CardOuterClass.internal_static_protocol_message_types_Card_descriptor;
      }

      public Card getDefaultInstanceForType() {
        return Card.getDefaultInstance();
      }

      public Card build() {
        Card result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Card buildPartial() {
        Card result = new Card(this);
        result.type_ = type_;
        result.label_ = label_;
        result.title_ = title_;
        result.subtitle_ = subtitle_;
        result.summary_ = summary_;
        result.image_ = image_;
        result.url_ = url_;
        result.display_ = display_;
        result.extra_ = extra_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Card) {
          return mergeFrom((Card)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Card other) {
        if (other == Card.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getSubtitle().isEmpty()) {
          subtitle_ = other.subtitle_;
          onChanged();
        }
        if (!other.getSummary().isEmpty()) {
          summary_ = other.summary_;
          onChanged();
        }
        if (!other.getImage().isEmpty()) {
          image_ = other.image_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getDisplay() != 0) {
          setDisplay(other.getDisplay());
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Card parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Card) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 卡片类型 由native约定
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 卡片类型 由native约定
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 卡片类型 由native约定
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object label_ = "";
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 2;</code>
       */
      public String getLabel() {
        Object ref = label_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 2;</code>
       */
      public Builder setLabel(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 2;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 2;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 3;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 3;</code>
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 3;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private Object subtitle_ = "";
      /**
       * <pre>
       * 副标题
       * </pre>
       *
       * <code>string subtitle = 4;</code>
       */
      public String getSubtitle() {
        Object ref = subtitle_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subtitle_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 副标题
       * </pre>
       *
       * <code>string subtitle = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubtitleBytes() {
        Object ref = subtitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subtitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 副标题
       * </pre>
       *
       * <code>string subtitle = 4;</code>
       */
      public Builder setSubtitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subtitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 副标题
       * </pre>
       *
       * <code>string subtitle = 4;</code>
       */
      public Builder clearSubtitle() {
        
        subtitle_ = getDefaultInstance().getSubtitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 副标题
       * </pre>
       *
       * <code>string subtitle = 4;</code>
       */
      public Builder setSubtitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subtitle_ = value;
        onChanged();
        return this;
      }

      private Object summary_ = "";
      /**
       * <pre>
       * 摘要
       * </pre>
       *
       * <code>string summary = 5;</code>
       */
      public String getSummary() {
        Object ref = summary_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 摘要
       * </pre>
       *
       * <code>string summary = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSummaryBytes() {
        Object ref = summary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          summary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 摘要
       * </pre>
       *
       * <code>string summary = 5;</code>
       */
      public Builder setSummary(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        summary_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 摘要
       * </pre>
       *
       * <code>string summary = 5;</code>
       */
      public Builder clearSummary() {
        
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 摘要
       * </pre>
       *
       * <code>string summary = 5;</code>
       */
      public Builder setSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        summary_ = value;
        onChanged();
        return this;
      }

      private Object image_ = "";
      /**
       * <pre>
       * 图片
       * </pre>
       *
       * <code>string image = 6;</code>
       */
      public String getImage() {
        Object ref = image_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 图片
       * </pre>
       *
       * <code>string image = 6;</code>
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 图片
       * </pre>
       *
       * <code>string image = 6;</code>
       */
      public Builder setImage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片
       * </pre>
       *
       * <code>string image = 6;</code>
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片
       * </pre>
       *
       * <code>string image = 6;</code>
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        image_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string url = 7;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string url = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string url = 7;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string url = 7;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 链接
       * </pre>
       *
       * <code>string url = 7;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int display_ ;
      /**
       * <pre>
       * 显示位置 0:系统消息会话; 1:toast only; 2:会话+toast
       * </pre>
       *
       * <code>int32 display = 8;</code>
       */
      public int getDisplay() {
        return display_;
      }
      /**
       * <pre>
       * 显示位置 0:系统消息会话; 1:toast only; 2:会话+toast
       * </pre>
       *
       * <code>int32 display = 8;</code>
       */
      public Builder setDisplay(int value) {
        
        display_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 显示位置 0:系统消息会话; 1:toast only; 2:会话+toast
       * </pre>
       *
       * <code>int32 display = 8;</code>
       */
      public Builder clearDisplay() {
        
        display_ = 0;
        onChanged();
        return this;
      }

      private Object extra_ = "";
      /**
       * <pre>
       * card 特定type的额外信息
       * </pre>
       *
       * <code>string extra = 9;</code>
       */
      public String getExtra() {
        Object ref = extra_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * card 特定type的额外信息
       * </pre>
       *
       * <code>string extra = 9;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * card 特定type的额外信息
       * </pre>
       *
       * <code>string extra = 9;</code>
       */
      public Builder setExtra(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * card 特定type的额外信息
       * </pre>
       *
       * <code>string extra = 9;</code>
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * card 特定type的额外信息
       * </pre>
       *
       * <code>string extra = 9;</code>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.types.Card)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.types.Card)
    private static final Card DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Card();
    }

    public static Card getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Card>
        PARSER = new com.google.protobuf.AbstractParser<Card>() {
      public Card parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Card(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Card> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Card> getParserForType() {
      return PARSER;
    }

    public Card getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_types_Card_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_types_Card_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020types/card.proto\022\026protocol.message.typ" +
      "es\"\221\001\n\004Card\022\014\n\004type\030\001 \001(\005\022\r\n\005label\030\002 \001(\t" +
      "\022\r\n\005title\030\003 \001(\t\022\020\n\010subtitle\030\004 \001(\t\022\017\n\007sum" +
      "mary\030\005 \001(\t\022\r\n\005image\030\006 \001(\t\022\013\n\003url\030\007 \001(\t\022\017" +
      "\n\007display\030\010 \001(\005\022\r\n\005extra\030\t \001(\tBD\n$com.me" +
      "dlinker.com.medlinker.protocol.message.typesZ\034grape/pr" +
      "otocol/message/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_message_types_Card_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_types_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_types_Card_descriptor,
        new String[] { "Type", "Label", "Title", "Subtitle", "Summary", "Image", "Url", "Display", "Extra", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
