// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/text.proto

package com.medlinker.protocol.message.types;

public final class TextOuterClass {
  private TextOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.types.Text)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    String getContent();
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    java.util.List<AnchorOuterClass.Anchor>
        getAnchorsList();
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    AnchorOuterClass.Anchor getAnchors(int index);
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    int getAnchorsCount();
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    java.util.List<? extends AnchorOuterClass.AnchorOrBuilder>
        getAnchorsOrBuilderList();
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    AnchorOuterClass.AnchorOrBuilder getAnchorsOrBuilder(
            int index);

    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> 
        getAtUsersList();
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    com.medlinker.protocol.message.misc.UserOuterClass.User getAtUsers(int index);
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    int getAtUsersCount();
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    java.util.List<? extends com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
        getAtUsersOrBuilderList();
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getAtUsersOrBuilder(
            int index);
  }
  /**
   * <pre>
   * 文本消息
   * </pre>
   *
   * Protobuf type {@code com.medlinker.protocol.message.types.Text}
   */
  public  static final class Text extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.types.Text)
      TextOrBuilder {
    // Use Text.newBuilder() to construct.
    private Text(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Text() {
      content_ = "";
      anchors_ = java.util.Collections.emptyList();
      atUsers_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Text(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                anchors_ = new java.util.ArrayList<AnchorOuterClass.Anchor>();
                mutable_bitField0_ |= 0x00000002;
              }
              anchors_.add(
                  input.readMessage(AnchorOuterClass.Anchor.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                atUsers_ = new java.util.ArrayList<com.medlinker.protocol.message.misc.UserOuterClass.User>();
                mutable_bitField0_ |= 0x00000004;
              }
              atUsers_.add(
                  input.readMessage(com.medlinker.protocol.message.misc.UserOuterClass.User.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          anchors_ = java.util.Collections.unmodifiableList(anchors_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          atUsers_ = java.util.Collections.unmodifiableList(atUsers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextOuterClass.internal_static_protocol_message_types_Text_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextOuterClass.internal_static_protocol_message_types_Text_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Text.class, Builder.class);
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile Object content_;
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANCHORS_FIELD_NUMBER = 2;
    private java.util.List<AnchorOuterClass.Anchor> anchors_;
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    public java.util.List<AnchorOuterClass.Anchor> getAnchorsList() {
      return anchors_;
    }
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    public java.util.List<? extends AnchorOuterClass.AnchorOrBuilder>
        getAnchorsOrBuilderList() {
      return anchors_;
    }
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    public int getAnchorsCount() {
      return anchors_.size();
    }
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    public AnchorOuterClass.Anchor getAnchors(int index) {
      return anchors_.get(index);
    }
    /**
     * <pre>
     * 5.1新增需求，文本中特么要夹带链接
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
     */
    public AnchorOuterClass.AnchorOrBuilder getAnchorsOrBuilder(
        int index) {
      return anchors_.get(index);
    }

    public static final int ATUSERS_FIELD_NUMBER = 3;
    private java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> atUsers_;
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    public java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> getAtUsersList() {
      return atUsers_;
    }
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    public java.util.List<? extends com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
        getAtUsersOrBuilderList() {
      return atUsers_;
    }
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    public int getAtUsersCount() {
      return atUsers_.size();
    }
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    public com.medlinker.protocol.message.misc.UserOuterClass.User getAtUsers(int index) {
      return atUsers_.get(index);
    }
    /**
     * <pre>
     * 5.2圈某人
     * </pre>
     *
     * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
     */
    public com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getAtUsersOrBuilder(
        int index) {
      return atUsers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      for (int i = 0; i < anchors_.size(); i++) {
        output.writeMessage(2, anchors_.get(i));
      }
      for (int i = 0; i < atUsers_.size(); i++) {
        output.writeMessage(3, atUsers_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      for (int i = 0; i < anchors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, anchors_.get(i));
      }
      for (int i = 0; i < atUsers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, atUsers_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Text)) {
        return super.equals(obj);
      }
      Text other = (Text) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && getAnchorsList()
          .equals(other.getAnchorsList());
      result = result && getAtUsersList()
          .equals(other.getAtUsersList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getAnchorsCount() > 0) {
        hash = (37 * hash) + ANCHORS_FIELD_NUMBER;
        hash = (53 * hash) + getAnchorsList().hashCode();
      }
      if (getAtUsersCount() > 0) {
        hash = (37 * hash) + ATUSERS_FIELD_NUMBER;
        hash = (53 * hash) + getAtUsersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Text parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Text parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Text parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Text parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Text parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Text parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Text parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Text parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Text parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Text parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Text prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 文本消息
     * </pre>
     *
     * Protobuf type {@code com.medlinker.protocol.message.types.Text}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.types.Text)
        TextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextOuterClass.internal_static_protocol_message_types_Text_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextOuterClass.internal_static_protocol_message_types_Text_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Text.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.types.TextOuterClass.Text.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAnchorsFieldBuilder();
          getAtUsersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";

        if (anchorsBuilder_ == null) {
          anchors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          anchorsBuilder_.clear();
        }
        if (atUsersBuilder_ == null) {
          atUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          atUsersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextOuterClass.internal_static_protocol_message_types_Text_descriptor;
      }

      public Text getDefaultInstanceForType() {
        return Text.getDefaultInstance();
      }

      public Text build() {
        Text result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Text buildPartial() {
        Text result = new Text(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.content_ = content_;
        if (anchorsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            anchors_ = java.util.Collections.unmodifiableList(anchors_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.anchors_ = anchors_;
        } else {
          result.anchors_ = anchorsBuilder_.build();
        }
        if (atUsersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            atUsers_ = java.util.Collections.unmodifiableList(atUsers_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.atUsers_ = atUsers_;
        } else {
          result.atUsers_ = atUsersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Text) {
          return mergeFrom((Text)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Text other) {
        if (other == Text.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (anchorsBuilder_ == null) {
          if (!other.anchors_.isEmpty()) {
            if (anchors_.isEmpty()) {
              anchors_ = other.anchors_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAnchorsIsMutable();
              anchors_.addAll(other.anchors_);
            }
            onChanged();
          }
        } else {
          if (!other.anchors_.isEmpty()) {
            if (anchorsBuilder_.isEmpty()) {
              anchorsBuilder_.dispose();
              anchorsBuilder_ = null;
              anchors_ = other.anchors_;
              bitField0_ = (bitField0_ & ~0x00000002);
              anchorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAnchorsFieldBuilder() : null;
            } else {
              anchorsBuilder_.addAllMessages(other.anchors_);
            }
          }
        }
        if (atUsersBuilder_ == null) {
          if (!other.atUsers_.isEmpty()) {
            if (atUsers_.isEmpty()) {
              atUsers_ = other.atUsers_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAtUsersIsMutable();
              atUsers_.addAll(other.atUsers_);
            }
            onChanged();
          }
        } else {
          if (!other.atUsers_.isEmpty()) {
            if (atUsersBuilder_.isEmpty()) {
              atUsersBuilder_.dispose();
              atUsersBuilder_ = null;
              atUsers_ = other.atUsers_;
              bitField0_ = (bitField0_ & ~0x00000004);
              atUsersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAtUsersFieldBuilder() : null;
            } else {
              atUsersBuilder_.addAllMessages(other.atUsers_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Text parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Text) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object content_ = "";
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.util.List<AnchorOuterClass.Anchor> anchors_ =
        java.util.Collections.emptyList();
      private void ensureAnchorsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          anchors_ = new java.util.ArrayList<AnchorOuterClass.Anchor>(anchors_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AnchorOuterClass.Anchor, AnchorOuterClass.Anchor.Builder, AnchorOuterClass.AnchorOrBuilder> anchorsBuilder_;

      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public java.util.List<AnchorOuterClass.Anchor> getAnchorsList() {
        if (anchorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(anchors_);
        } else {
          return anchorsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public int getAnchorsCount() {
        if (anchorsBuilder_ == null) {
          return anchors_.size();
        } else {
          return anchorsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public AnchorOuterClass.Anchor getAnchors(int index) {
        if (anchorsBuilder_ == null) {
          return anchors_.get(index);
        } else {
          return anchorsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder setAnchors(
          int index, AnchorOuterClass.Anchor value) {
        if (anchorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnchorsIsMutable();
          anchors_.set(index, value);
          onChanged();
        } else {
          anchorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder setAnchors(
          int index, AnchorOuterClass.Anchor.Builder builderForValue) {
        if (anchorsBuilder_ == null) {
          ensureAnchorsIsMutable();
          anchors_.set(index, builderForValue.build());
          onChanged();
        } else {
          anchorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder addAnchors(AnchorOuterClass.Anchor value) {
        if (anchorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnchorsIsMutable();
          anchors_.add(value);
          onChanged();
        } else {
          anchorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder addAnchors(
          int index, AnchorOuterClass.Anchor value) {
        if (anchorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnchorsIsMutable();
          anchors_.add(index, value);
          onChanged();
        } else {
          anchorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder addAnchors(
          AnchorOuterClass.Anchor.Builder builderForValue) {
        if (anchorsBuilder_ == null) {
          ensureAnchorsIsMutable();
          anchors_.add(builderForValue.build());
          onChanged();
        } else {
          anchorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder addAnchors(
          int index, AnchorOuterClass.Anchor.Builder builderForValue) {
        if (anchorsBuilder_ == null) {
          ensureAnchorsIsMutable();
          anchors_.add(index, builderForValue.build());
          onChanged();
        } else {
          anchorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder addAllAnchors(
          Iterable<? extends AnchorOuterClass.Anchor> values) {
        if (anchorsBuilder_ == null) {
          ensureAnchorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, anchors_);
          onChanged();
        } else {
          anchorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder clearAnchors() {
        if (anchorsBuilder_ == null) {
          anchors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          anchorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public Builder removeAnchors(int index) {
        if (anchorsBuilder_ == null) {
          ensureAnchorsIsMutable();
          anchors_.remove(index);
          onChanged();
        } else {
          anchorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public AnchorOuterClass.Anchor.Builder getAnchorsBuilder(
          int index) {
        return getAnchorsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public AnchorOuterClass.AnchorOrBuilder getAnchorsOrBuilder(
          int index) {
        if (anchorsBuilder_ == null) {
          return anchors_.get(index);  } else {
          return anchorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public java.util.List<? extends AnchorOuterClass.AnchorOrBuilder>
           getAnchorsOrBuilderList() {
        if (anchorsBuilder_ != null) {
          return anchorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(anchors_);
        }
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public AnchorOuterClass.Anchor.Builder addAnchorsBuilder() {
        return getAnchorsFieldBuilder().addBuilder(
            AnchorOuterClass.Anchor.getDefaultInstance());
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public AnchorOuterClass.Anchor.Builder addAnchorsBuilder(
          int index) {
        return getAnchorsFieldBuilder().addBuilder(
            index, AnchorOuterClass.Anchor.getDefaultInstance());
      }
      /**
       * <pre>
       * 5.1新增需求，文本中特么要夹带链接
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.types.Anchor anchors = 2;</code>
       */
      public java.util.List<AnchorOuterClass.Anchor.Builder>
           getAnchorsBuilderList() {
        return getAnchorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AnchorOuterClass.Anchor, AnchorOuterClass.Anchor.Builder, AnchorOuterClass.AnchorOrBuilder>
          getAnchorsFieldBuilder() {
        if (anchorsBuilder_ == null) {
          anchorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AnchorOuterClass.Anchor, AnchorOuterClass.Anchor.Builder, AnchorOuterClass.AnchorOrBuilder>(
                  anchors_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          anchors_ = null;
        }
        return anchorsBuilder_;
      }

      private java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> atUsers_ =
        java.util.Collections.emptyList();
      private void ensureAtUsersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          atUsers_ = new java.util.ArrayList<com.medlinker.protocol.message.misc.UserOuterClass.User>(atUsers_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> atUsersBuilder_;

      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> getAtUsersList() {
        if (atUsersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(atUsers_);
        } else {
          return atUsersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public int getAtUsersCount() {
        if (atUsersBuilder_ == null) {
          return atUsers_.size();
        } else {
          return atUsersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User getAtUsers(int index) {
        if (atUsersBuilder_ == null) {
          return atUsers_.get(index);
        } else {
          return atUsersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder setAtUsers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (atUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtUsersIsMutable();
          atUsers_.set(index, value);
          onChanged();
        } else {
          atUsersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder setAtUsers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (atUsersBuilder_ == null) {
          ensureAtUsersIsMutable();
          atUsers_.set(index, builderForValue.build());
          onChanged();
        } else {
          atUsersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder addAtUsers(com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (atUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtUsersIsMutable();
          atUsers_.add(value);
          onChanged();
        } else {
          atUsersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder addAtUsers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (atUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtUsersIsMutable();
          atUsers_.add(index, value);
          onChanged();
        } else {
          atUsersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder addAtUsers(
          com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (atUsersBuilder_ == null) {
          ensureAtUsersIsMutable();
          atUsers_.add(builderForValue.build());
          onChanged();
        } else {
          atUsersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder addAtUsers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (atUsersBuilder_ == null) {
          ensureAtUsersIsMutable();
          atUsers_.add(index, builderForValue.build());
          onChanged();
        } else {
          atUsersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder addAllAtUsers(
          Iterable<? extends com.medlinker.protocol.message.misc.UserOuterClass.User> values) {
        if (atUsersBuilder_ == null) {
          ensureAtUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, atUsers_);
          onChanged();
        } else {
          atUsersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder clearAtUsers() {
        if (atUsersBuilder_ == null) {
          atUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          atUsersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public Builder removeAtUsers(int index) {
        if (atUsersBuilder_ == null) {
          ensureAtUsersIsMutable();
          atUsers_.remove(index);
          onChanged();
        } else {
          atUsersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder getAtUsersBuilder(
          int index) {
        return getAtUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getAtUsersOrBuilder(
          int index) {
        if (atUsersBuilder_ == null) {
          return atUsers_.get(index);  } else {
          return atUsersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public java.util.List<? extends com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
           getAtUsersOrBuilderList() {
        if (atUsersBuilder_ != null) {
          return atUsersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(atUsers_);
        }
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder addAtUsersBuilder() {
        return getAtUsersFieldBuilder().addBuilder(
            com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder addAtUsersBuilder(
          int index) {
        return getAtUsersFieldBuilder().addBuilder(
            index, com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <pre>
       * 5.2圈某人
       * </pre>
       *
       * <code>repeated .com.medlinker.protocol.message.misc.User atUsers = 3;</code>
       */
      public java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User.Builder> 
           getAtUsersBuilderList() {
        return getAtUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
          getAtUsersFieldBuilder() {
        if (atUsersBuilder_ == null) {
          atUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder>(
                  atUsers_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          atUsers_ = null;
        }
        return atUsersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.types.Text)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.types.Text)
    private static final Text DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Text();
    }

    public static Text getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Text>
        PARSER = new com.google.protobuf.AbstractParser<Text>() {
      public Text parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Text(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Text> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Text> getParserForType() {
      return PARSER;
    }

    public Text getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_types_Text_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_types_Text_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020types/text.proto\022\026protocol.message.typ" +
      "es\032\022types/anchor.proto\032\017misc/user.proto\"" +
      "v\n\004Text\022\017\n\007content\030\001 \001(\t\022/\n\007anchors\030\002 \003(" +
      "\0132\036.com.medlinker.protocol.message.types.Anchor\022,\n\007atU" +
      "sers\030\003 \003(\0132\033.com.medlinker.protocol.message.misc.UserB" +
      "D\n$com.medlinker.com.medlinker.protocol.message.typesZ" +
      "\034grape/protocol/message/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AnchorOuterClass.getDescriptor(),
          com.medlinker.protocol.message.misc.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protocol_message_types_Text_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_types_Text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_types_Text_descriptor,
        new String[] { "Content", "Anchors", "AtUsers", });
    AnchorOuterClass.getDescriptor();
    com.medlinker.protocol.message.misc.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
