// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands/friend_operation.proto

package com.medlinker.protocol.message.commands;

public final class FriendOperationOuterClass {
  private FriendOperationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FriendOperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.commands.FriendOperation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 操作类型 0-添加 1-同意 2-拒绝 3-拉黑 9=忽略
     * </pre>
     *
     * <code>int32 operation = 1;</code>
     */
    int getOperation();

    /**
     * <pre>
     * 对方id(仅支持医生/机构，所以无需type)
     * </pre>
     *
     * <code>int64 opposite = 2;</code>
     */
    long getOpposite();

    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    String getContent();
    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 来源 0=通讯录 1=通过手机号搜索 2=通过群 3=通过二维码 4=通过名片 5=通过主页
     * </pre>
     *
     * <code>int32 reference = 4;</code>
     */
    int getReference();
  }
  /**
   * Protobuf type {@code com.medlinker.protocol.message.commands.FriendOperation}
   */
  public  static final class FriendOperation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.commands.FriendOperation)
      FriendOperationOrBuilder {
    // Use FriendOperation.newBuilder() to construct.
    private FriendOperation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FriendOperation() {
      operation_ = 0;
      opposite_ = 0L;
      content_ = "";
      reference_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FriendOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              operation_ = input.readInt32();
              break;
            }
            case 16: {

              opposite_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              reference_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FriendOperationOuterClass.internal_static_protocol_message_commands_FriendOperation_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FriendOperationOuterClass.internal_static_protocol_message_commands_FriendOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FriendOperation.class, Builder.class);
    }

    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <pre>
     * 操作类型 0-添加 1-同意 2-拒绝 3-拉黑 9=忽略
     * </pre>
     *
     * <code>int32 operation = 1;</code>
     */
    public int getOperation() {
      return operation_;
    }

    public static final int OPPOSITE_FIELD_NUMBER = 2;
    private long opposite_;
    /**
     * <pre>
     * 对方id(仅支持医生/机构，所以无需type)
     * </pre>
     *
     * <code>int64 opposite = 2;</code>
     */
    public long getOpposite() {
      return opposite_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile Object content_;
    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCE_FIELD_NUMBER = 4;
    private int reference_;
    /**
     * <pre>
     * 来源 0=通讯录 1=通过手机号搜索 2=通过群 3=通过二维码 4=通过名片 5=通过主页
     * </pre>
     *
     * <code>int32 reference = 4;</code>
     */
    public int getReference() {
      return reference_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operation_ != 0) {
        output.writeInt32(1, operation_);
      }
      if (opposite_ != 0L) {
        output.writeInt64(2, opposite_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (reference_ != 0) {
        output.writeInt32(4, reference_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, operation_);
      }
      if (opposite_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, opposite_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (reference_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, reference_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FriendOperation)) {
        return super.equals(obj);
      }
      FriendOperation other = (FriendOperation) obj;

      boolean result = true;
      result = result && (getOperation()
          == other.getOperation());
      result = result && (getOpposite()
          == other.getOpposite());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getReference()
          == other.getReference());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation();
      hash = (37 * hash) + OPPOSITE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOpposite());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + REFERENCE_FIELD_NUMBER;
      hash = (53 * hash) + getReference();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FriendOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FriendOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FriendOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FriendOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FriendOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FriendOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FriendOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FriendOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FriendOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FriendOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FriendOperation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.medlinker.protocol.message.commands.FriendOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.commands.FriendOperation)
        FriendOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FriendOperationOuterClass.internal_static_protocol_message_commands_FriendOperation_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FriendOperationOuterClass.internal_static_protocol_message_commands_FriendOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FriendOperation.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.commands.FriendOperationOuterClass.FriendOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        operation_ = 0;

        opposite_ = 0L;

        content_ = "";

        reference_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FriendOperationOuterClass.internal_static_protocol_message_commands_FriendOperation_descriptor;
      }

      public FriendOperation getDefaultInstanceForType() {
        return FriendOperation.getDefaultInstance();
      }

      public FriendOperation build() {
        FriendOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FriendOperation buildPartial() {
        FriendOperation result = new FriendOperation(this);
        result.operation_ = operation_;
        result.opposite_ = opposite_;
        result.content_ = content_;
        result.reference_ = reference_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FriendOperation) {
          return mergeFrom((FriendOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FriendOperation other) {
        if (other == FriendOperation.getDefaultInstance()) return this;
        if (other.getOperation() != 0) {
          setOperation(other.getOperation());
        }
        if (other.getOpposite() != 0L) {
          setOpposite(other.getOpposite());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getReference() != 0) {
          setReference(other.getReference());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FriendOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FriendOperation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int operation_ ;
      /**
       * <pre>
       * 操作类型 0-添加 1-同意 2-拒绝 3-拉黑 9=忽略
       * </pre>
       *
       * <code>int32 operation = 1;</code>
       */
      public int getOperation() {
        return operation_;
      }
      /**
       * <pre>
       * 操作类型 0-添加 1-同意 2-拒绝 3-拉黑 9=忽略
       * </pre>
       *
       * <code>int32 operation = 1;</code>
       */
      public Builder setOperation(int value) {
        
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型 0-添加 1-同意 2-拒绝 3-拉黑 9=忽略
       * </pre>
       *
       * <code>int32 operation = 1;</code>
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private long opposite_ ;
      /**
       * <pre>
       * 对方id(仅支持医生/机构，所以无需type)
       * </pre>
       *
       * <code>int64 opposite = 2;</code>
       */
      public long getOpposite() {
        return opposite_;
      }
      /**
       * <pre>
       * 对方id(仅支持医生/机构，所以无需type)
       * </pre>
       *
       * <code>int64 opposite = 2;</code>
       */
      public Builder setOpposite(long value) {
        
        opposite_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对方id(仅支持医生/机构，所以无需type)
       * </pre>
       *
       * <code>int64 opposite = 2;</code>
       */
      public Builder clearOpposite() {
        
        opposite_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int reference_ ;
      /**
       * <pre>
       * 来源 0=通讯录 1=通过手机号搜索 2=通过群 3=通过二维码 4=通过名片 5=通过主页
       * </pre>
       *
       * <code>int32 reference = 4;</code>
       */
      public int getReference() {
        return reference_;
      }
      /**
       * <pre>
       * 来源 0=通讯录 1=通过手机号搜索 2=通过群 3=通过二维码 4=通过名片 5=通过主页
       * </pre>
       *
       * <code>int32 reference = 4;</code>
       */
      public Builder setReference(int value) {
        
        reference_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源 0=通讯录 1=通过手机号搜索 2=通过群 3=通过二维码 4=通过名片 5=通过主页
       * </pre>
       *
       * <code>int32 reference = 4;</code>
       */
      public Builder clearReference() {
        
        reference_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.commands.FriendOperation)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.commands.FriendOperation)
    private static final FriendOperation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FriendOperation();
    }

    public static FriendOperation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FriendOperation>
        PARSER = new com.google.protobuf.AbstractParser<FriendOperation>() {
      public FriendOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FriendOperation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FriendOperation> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FriendOperation> getParserForType() {
      return PARSER;
    }

    public FriendOperation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_commands_FriendOperation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_commands_FriendOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037commands/friend_operation.proto\022\031proto" +
      "col.message.commands\"Z\n\017FriendOperation\022" +
      "\021\n\toperation\030\001 \001(\005\022\020\n\010opposite\030\002 \001(\003\022\017\n\007" +
      "content\030\003 \001(\t\022\021\n\treference\030\004 \001(\005BJ\n\'com." +
      "medlinker.com.medlinker.protocol.message.commandsZ\037gra" +
      "pe/protocol/message/commandsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_message_commands_FriendOperation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_commands_FriendOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_commands_FriendOperation_descriptor,
        new String[] { "Operation", "Opposite", "Content", "Reference", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
