// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands/group_operation.proto

package com.medlinker.protocol.message.commands;

public final class GroupOperationOuterClass {
  private GroupOperationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupOperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.commands.GroupOperation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 操作 0=创建群 1=邀请 2=退群(踢人) 3=加群申请 4=同意加群 5=忽略
     * </pre>
     *
     * <code>int32 operation = 1;</code>
     */
    int getOperation();

    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>int64 group = 2;</code>
     */
    long getGroup();

    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> 
        getMembersList();
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    com.medlinker.protocol.message.misc.UserOuterClass.User getMembers(int index);
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    java.util.List<? extends com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
        getMembersOrBuilderList();
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getMembersOrBuilder(
            int index);

    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    String getContent();
    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.medlinker.protocol.message.commands.GroupOperation}
   */
  public  static final class GroupOperation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.commands.GroupOperation)
      GroupOperationOrBuilder {
    // Use GroupOperation.newBuilder() to construct.
    private GroupOperation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupOperation() {
      operation_ = 0;
      group_ = 0L;
      members_ = java.util.Collections.emptyList();
      content_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GroupOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              operation_ = input.readInt32();
              break;
            }
            case 16: {

              group_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                members_ = new java.util.ArrayList<com.medlinker.protocol.message.misc.UserOuterClass.User>();
                mutable_bitField0_ |= 0x00000004;
              }
              members_.add(
                  input.readMessage(com.medlinker.protocol.message.misc.UserOuterClass.User.parser(), extensionRegistry));
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = java.util.Collections.unmodifiableList(members_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GroupOperationOuterClass.internal_static_protocol_message_commands_GroupOperation_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GroupOperationOuterClass.internal_static_protocol_message_commands_GroupOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GroupOperation.class, Builder.class);
    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <pre>
     * 操作 0=创建群 1=邀请 2=退群(踢人) 3=加群申请 4=同意加群 5=忽略
     * </pre>
     *
     * <code>int32 operation = 1;</code>
     */
    public int getOperation() {
      return operation_;
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private long group_;
    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>int64 group = 2;</code>
     */
    public long getGroup() {
      return group_;
    }

    public static final int MEMBERS_FIELD_NUMBER = 3;
    private java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> members_;
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    public java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> getMembersList() {
      return members_;
    }
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    public java.util.List<? extends com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
        getMembersOrBuilderList() {
      return members_;
    }
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    public com.medlinker.protocol.message.misc.UserOuterClass.User getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
     */
    public com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getMembersOrBuilder(
        int index) {
      return members_.get(index);
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile Object content_;
    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求附属消息
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operation_ != 0) {
        output.writeInt32(1, operation_);
      }
      if (group_ != 0L) {
        output.writeInt64(2, group_);
      }
      for (int i = 0; i < members_.size(); i++) {
        output.writeMessage(3, members_.get(i));
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, operation_);
      }
      if (group_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, group_);
      }
      for (int i = 0; i < members_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, members_.get(i));
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GroupOperation)) {
        return super.equals(obj);
      }
      GroupOperation other = (GroupOperation) obj;

      boolean result = true;
      result = result && (getOperation()
          == other.getOperation());
      result = result && (getGroup()
          == other.getGroup());
      result = result && getMembersList()
          .equals(other.getMembersList());
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroup());
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GroupOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GroupOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GroupOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GroupOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GroupOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GroupOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GroupOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GroupOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GroupOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GroupOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GroupOperation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.medlinker.protocol.message.commands.GroupOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.commands.GroupOperation)
        GroupOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GroupOperationOuterClass.internal_static_protocol_message_commands_GroupOperation_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GroupOperationOuterClass.internal_static_protocol_message_commands_GroupOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GroupOperation.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.commands.GroupOperationOuterClass.GroupOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMembersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        operation_ = 0;

        group_ = 0L;

        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          membersBuilder_.clear();
        }
        content_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GroupOperationOuterClass.internal_static_protocol_message_commands_GroupOperation_descriptor;
      }

      public GroupOperation getDefaultInstanceForType() {
        return GroupOperation.getDefaultInstance();
      }

      public GroupOperation build() {
        GroupOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GroupOperation buildPartial() {
        GroupOperation result = new GroupOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.operation_ = operation_;
        result.group_ = group_;
        if (membersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            members_ = java.util.Collections.unmodifiableList(members_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.members_ = members_;
        } else {
          result.members_ = membersBuilder_.build();
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GroupOperation) {
          return mergeFrom((GroupOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GroupOperation other) {
        if (other == GroupOperation.getDefaultInstance()) return this;
        if (other.getOperation() != 0) {
          setOperation(other.getOperation());
        }
        if (other.getGroup() != 0L) {
          setGroup(other.getGroup());
        }
        if (membersBuilder_ == null) {
          if (!other.members_.isEmpty()) {
            if (members_.isEmpty()) {
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMembersIsMutable();
              members_.addAll(other.members_);
            }
            onChanged();
          }
        } else {
          if (!other.members_.isEmpty()) {
            if (membersBuilder_.isEmpty()) {
              membersBuilder_.dispose();
              membersBuilder_ = null;
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000004);
              membersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMembersFieldBuilder() : null;
            } else {
              membersBuilder_.addAllMessages(other.members_);
            }
          }
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GroupOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GroupOperation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int operation_ ;
      /**
       * <pre>
       * 操作 0=创建群 1=邀请 2=退群(踢人) 3=加群申请 4=同意加群 5=忽略
       * </pre>
       *
       * <code>int32 operation = 1;</code>
       */
      public int getOperation() {
        return operation_;
      }
      /**
       * <pre>
       * 操作 0=创建群 1=邀请 2=退群(踢人) 3=加群申请 4=同意加群 5=忽略
       * </pre>
       *
       * <code>int32 operation = 1;</code>
       */
      public Builder setOperation(int value) {
        
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作 0=创建群 1=邀请 2=退群(踢人) 3=加群申请 4=同意加群 5=忽略
       * </pre>
       *
       * <code>int32 operation = 1;</code>
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private long group_ ;
      /**
       * <pre>
       * group id
       * </pre>
       *
       * <code>int64 group = 2;</code>
       */
      public long getGroup() {
        return group_;
      }
      /**
       * <pre>
       * group id
       * </pre>
       *
       * <code>int64 group = 2;</code>
       */
      public Builder setGroup(long value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * group id
       * </pre>
       *
       * <code>int64 group = 2;</code>
       */
      public Builder clearGroup() {
        
        group_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> members_ =
        java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = new java.util.ArrayList<com.medlinker.protocol.message.misc.UserOuterClass.User>(members_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> membersBuilder_;

      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User> getMembersList() {
        if (membersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(members_);
        } else {
          return membersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public int getMembersCount() {
        if (membersBuilder_ == null) {
          return members_.size();
        } else {
          return membersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User getMembers(int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);
        } else {
          return membersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder setMembers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.set(index, value);
          onChanged();
        } else {
          membersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder setMembers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.set(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder addMembers(com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(value);
          onChanged();
        } else {
          membersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder addMembers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(index, value);
          onChanged();
        } else {
          membersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder addMembers(
          com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder addMembers(
          int index, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder addAllMembers(
          Iterable<? extends com.medlinker.protocol.message.misc.UserOuterClass.User> values) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, members_);
          onChanged();
        } else {
          membersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder clearMembers() {
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          membersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public Builder removeMembers(int index) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.remove(index);
          onChanged();
        } else {
          membersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder getMembersBuilder(
          int index) {
        return getMembersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder getMembersOrBuilder(
          int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);  } else {
          return membersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public java.util.List<? extends com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
           getMembersOrBuilderList() {
        if (membersBuilder_ != null) {
          return membersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(members_);
        }
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder addMembersBuilder() {
        return getMembersFieldBuilder().addBuilder(
            com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public com.medlinker.protocol.message.misc.UserOuterClass.User.Builder addMembersBuilder(
          int index) {
        return getMembersFieldBuilder().addBuilder(
            index, com.medlinker.protocol.message.misc.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <code>repeated .com.medlinker.protocol.message.misc.User members = 3;</code>
       */
      public java.util.List<com.medlinker.protocol.message.misc.UserOuterClass.User.Builder> 
           getMembersBuilderList() {
        return getMembersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder> 
          getMembersFieldBuilder() {
        if (membersBuilder_ == null) {
          membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.medlinker.protocol.message.misc.UserOuterClass.User, com.medlinker.protocol.message.misc.UserOuterClass.User.Builder, com.medlinker.protocol.message.misc.UserOuterClass.UserOrBuilder>(
                  members_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          members_ = null;
        }
        return membersBuilder_;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求附属消息
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.commands.GroupOperation)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.commands.GroupOperation)
    private static final GroupOperation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GroupOperation();
    }

    public static GroupOperation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupOperation>
        PARSER = new com.google.protobuf.AbstractParser<GroupOperation>() {
      public GroupOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GroupOperation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupOperation> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GroupOperation> getParserForType() {
      return PARSER;
    }

    public GroupOperation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_commands_GroupOperation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_commands_GroupOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036commands/group_operation.proto\022\031protoc" +
      "ol.message.commands\032\017misc/user.proto\"q\n\016" +
      "GroupOperation\022\021\n\toperation\030\001 \001(\005\022\r\n\005gro" +
      "up\030\002 \001(\003\022,\n\007members\030\003 \003(\0132\033.protocol.mes" +
      "sage.misc.User\022\017\n\007content\030\004 \001(\tBJ\n\'com.m" +
      "edlinker.com.medlinker.protocol.message.commandsZ\037grap" +
      "e/protocol/message/commandsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.medlinker.protocol.message.misc.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protocol_message_commands_GroupOperation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_commands_GroupOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_commands_GroupOperation_descriptor,
        new String[] { "Operation", "Group", "Members", "Content", });
    com.medlinker.protocol.message.misc.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
