// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands/login.proto

package com.medlinker.protocol.message.commands;

public final class LoginOuterClass {
  private LoginOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.commands.Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 设备多端登录使用 0-手机 1-电脑
     * </pre>
     *
     * <code>int32 device = 1;</code>
     */
    int getDevice();

    /**
     * <pre>
     * 操作平台 0-android 1-ios 2-web
     * </pre>
     *
     * <code>int32 platform = 2;</code>
     */
    int getPlatform();

    /**
     * <pre>
     * 建立连接时服务端发送的token
     * </pre>
     *
     * <code>string token = 3;</code>
     */
    String getToken();
    /**
     * <pre>
     * 建立连接时服务端发送的token
     * </pre>
     *
     * <code>string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     * client session key
     * </pre>
     *
     * <code>string session_key = 4;</code>
     */
    String getSessionKey();
    /**
     * <pre>
     * client session key
     * </pre>
     *
     * <code>string session_key = 4;</code>
     */
    com.google.protobuf.ByteString
        getSessionKeyBytes();

    /**
     * <pre>
     * 客户端版本
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    String getVersion();
    /**
     * <pre>
     * 客户端版本
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();
  }
  /**
   * Protobuf type {@code com.medlinker.protocol.message.commands.Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.commands.Login)
      LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      device_ = 0;
      platform_ = 0;
      token_ = "";
      sessionKey_ = "";
      version_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              device_ = input.readInt32();
              break;
            }
            case 16: {

              platform_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              sessionKey_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginOuterClass.internal_static_protocol_message_commands_Login_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginOuterClass.internal_static_protocol_message_commands_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Login.class, Builder.class);
    }

    public static final int DEVICE_FIELD_NUMBER = 1;
    private int device_;
    /**
     * <pre>
     * 设备多端登录使用 0-手机 1-电脑
     * </pre>
     *
     * <code>int32 device = 1;</code>
     */
    public int getDevice() {
      return device_;
    }

    public static final int PLATFORM_FIELD_NUMBER = 2;
    private int platform_;
    /**
     * <pre>
     * 操作平台 0-android 1-ios 2-web
     * </pre>
     *
     * <code>int32 platform = 2;</code>
     */
    public int getPlatform() {
      return platform_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile Object token_;
    /**
     * <pre>
     * 建立连接时服务端发送的token
     * </pre>
     *
     * <code>string token = 3;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 建立连接时服务端发送的token
     * </pre>
     *
     * <code>string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_KEY_FIELD_NUMBER = 4;
    private volatile Object sessionKey_;
    /**
     * <pre>
     * client session key
     * </pre>
     *
     * <code>string session_key = 4;</code>
     */
    public String getSessionKey() {
      Object ref = sessionKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * client session key
     * </pre>
     *
     * <code>string session_key = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSessionKeyBytes() {
      Object ref = sessionKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private volatile Object version_;
    /**
     * <pre>
     * 客户端版本
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 客户端版本
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (device_ != 0) {
        output.writeInt32(1, device_);
      }
      if (platform_ != 0) {
        output.writeInt32(2, platform_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (!getSessionKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sessionKey_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, version_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (device_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, device_);
      }
      if (platform_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, platform_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (!getSessionKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sessionKey_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, version_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Login)) {
        return super.equals(obj);
      }
      Login other = (Login) obj;

      boolean result = true;
      result = result && (getDevice()
          == other.getDevice());
      result = result && (getPlatform()
          == other.getPlatform());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getSessionKey()
          .equals(other.getSessionKey());
      result = result && getVersion()
          .equals(other.getVersion());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_FIELD_NUMBER;
      hash = (53 * hash) + getDevice();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + SESSION_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getSessionKey().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.medlinker.protocol.message.commands.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.commands.Login)
        LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginOuterClass.internal_static_protocol_message_commands_Login_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginOuterClass.internal_static_protocol_message_commands_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Login.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.commands.LoginOuterClass.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        device_ = 0;

        platform_ = 0;

        token_ = "";

        sessionKey_ = "";

        version_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginOuterClass.internal_static_protocol_message_commands_Login_descriptor;
      }

      public Login getDefaultInstanceForType() {
        return Login.getDefaultInstance();
      }

      public Login build() {
        Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Login buildPartial() {
        Login result = new Login(this);
        result.device_ = device_;
        result.platform_ = platform_;
        result.token_ = token_;
        result.sessionKey_ = sessionKey_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Login) {
          return mergeFrom((Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Login other) {
        if (other == Login.getDefaultInstance()) return this;
        if (other.getDevice() != 0) {
          setDevice(other.getDevice());
        }
        if (other.getPlatform() != 0) {
          setPlatform(other.getPlatform());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getSessionKey().isEmpty()) {
          sessionKey_ = other.sessionKey_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int device_ ;
      /**
       * <pre>
       * 设备多端登录使用 0-手机 1-电脑
       * </pre>
       *
       * <code>int32 device = 1;</code>
       */
      public int getDevice() {
        return device_;
      }
      /**
       * <pre>
       * 设备多端登录使用 0-手机 1-电脑
       * </pre>
       *
       * <code>int32 device = 1;</code>
       */
      public Builder setDevice(int value) {
        
        device_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备多端登录使用 0-手机 1-电脑
       * </pre>
       *
       * <code>int32 device = 1;</code>
       */
      public Builder clearDevice() {
        
        device_ = 0;
        onChanged();
        return this;
      }

      private int platform_ ;
      /**
       * <pre>
       * 操作平台 0-android 1-ios 2-web
       * </pre>
       *
       * <code>int32 platform = 2;</code>
       */
      public int getPlatform() {
        return platform_;
      }
      /**
       * <pre>
       * 操作平台 0-android 1-ios 2-web
       * </pre>
       *
       * <code>int32 platform = 2;</code>
       */
      public Builder setPlatform(int value) {
        
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作平台 0-android 1-ios 2-web
       * </pre>
       *
       * <code>int32 platform = 2;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = 0;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <pre>
       * 建立连接时服务端发送的token
       * </pre>
       *
       * <code>string token = 3;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 建立连接时服务端发送的token
       * </pre>
       *
       * <code>string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 建立连接时服务端发送的token
       * </pre>
       *
       * <code>string token = 3;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建立连接时服务端发送的token
       * </pre>
       *
       * <code>string token = 3;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建立连接时服务端发送的token
       * </pre>
       *
       * <code>string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private Object sessionKey_ = "";
      /**
       * <pre>
       * client session key
       * </pre>
       *
       * <code>string session_key = 4;</code>
       */
      public String getSessionKey() {
        Object ref = sessionKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * client session key
       * </pre>
       *
       * <code>string session_key = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSessionKeyBytes() {
        Object ref = sessionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * client session key
       * </pre>
       *
       * <code>string session_key = 4;</code>
       */
      public Builder setSessionKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client session key
       * </pre>
       *
       * <code>string session_key = 4;</code>
       */
      public Builder clearSessionKey() {
        
        sessionKey_ = getDefaultInstance().getSessionKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client session key
       * </pre>
       *
       * <code>string session_key = 4;</code>
       */
      public Builder setSessionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionKey_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <pre>
       * 客户端版本
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 客户端版本
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 客户端版本
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端版本
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端版本
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.commands.Login)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.commands.Login)
    private static final Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Login();
    }

    public static Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    public Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_commands_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_commands_Login_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024commands/login.proto\022\031protocol.message" +
      ".commands\"^\n\005Login\022\016\n\006device\030\001 \001(\005\022\020\n\010pl" +
      "atform\030\002 \001(\005\022\r\n\005token\030\003 \001(\t\022\023\n\013session_k" +
      "ey\030\004 \001(\t\022\017\n\007version\030\005 \001(\tBJ\n\'com.medlink" +
      "er.com.medlinker.protocol.message.commandsZ\037grape/prot" +
      "ocol/message/commandsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_message_commands_Login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_commands_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_commands_Login_descriptor,
        new String[] { "Device", "Platform", "Token", "SessionKey", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
