// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc/group.proto

package com.medlinker.protocol.message.misc;

public final class GroupOuterClass {
  private GroupOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.medlinker.protocol.message.misc.Group)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 3;</code>
     */
    String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    java.util.List<String>
        getAvatarList();
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    int getAvatarCount();
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    String getAvatar(int index);
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes(int index);

    /**
     * <pre>
     * 群人数
     * </pre>
     *
     * <code>int32 amount = 5;</code>
     */
    int getAmount();

    /**
     * <pre>
     * 群主，只能为医联主库用户
     * </pre>
     *
     * <code>int64 owner = 6;</code>
     */
    long getOwner();

    /**
     * <pre>
     *  群业务类型  0：普通群 1：问诊
     * </pre>
     *
     * <code>int32 businessType = 7;</code>
     */
    int getBusinessType();

    /**
     * <pre>
     *  群业务id   如businessType！=0.则businessId 为具体业务业务id
     * </pre>
     *
     * <code>int64 businessId = 8;</code>
     */
    long getBusinessId();

    /**
     * <pre>
     *用户设置的头像
     * </pre>
     *
     * <code>string avatarUrl = 9;</code>
     */
    String getAvatarUrl();
    /**
     * <pre>
     *用户设置的头像
     * </pre>
     *
     * <code>string avatarUrl = 9;</code>
     */
    com.google.protobuf.ByteString
        getAvatarUrlBytes();

    /**
     * <pre>
     * 是否公开群
     * </pre>
     *
     * <code>int32 isPublic = 10;</code>
     */
    int getIsPublic();

    /**
     * <pre>
     * 是否被屏蔽
     * </pre>
     *
     * <code>int32 isForbidden = 11;</code>
     */
    int getIsForbidden();
  }
  /**
   * Protobuf type {@code com.medlinker.protocol.message.misc.Group}
   */
  public  static final class Group extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.medlinker.protocol.message.misc.Group)
      GroupOrBuilder {
    // Use Group.newBuilder() to construct.
    private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Group() {
      id_ = 0L;
      name_ = "";
      avatar_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      amount_ = 0;
      owner_ = 0L;
      businessType_ = 0;
      businessId_ = 0L;
      avatarUrl_ = "";
      isPublic_ = 0;
      isForbidden_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Group(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                avatar_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              avatar_.add(s);
              break;
            }
            case 40: {

              amount_ = input.readInt32();
              break;
            }
            case 48: {

              owner_ = input.readInt64();
              break;
            }
            case 56: {

              businessType_ = input.readInt32();
              break;
            }
            case 64: {

              businessId_ = input.readInt64();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              avatarUrl_ = s;
              break;
            }
            case 80: {

              isPublic_ = input.readInt32();
              break;
            }
            case 88: {

              isForbidden_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          avatar_ = avatar_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GroupOuterClass.internal_static_protocol_message_misc_Group_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GroupOuterClass.internal_static_protocol_message_misc_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Group.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList avatar_;
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAvatarList() {
      return avatar_;
    }
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    public int getAvatarCount() {
      return avatar_.size();
    }
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    public String getAvatar(int index) {
      return avatar_.get(index);
    }
    /**
     * <pre>
     * 很多个用户的头像
     * </pre>
     *
     * <code>repeated string avatar = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes(int index) {
      return avatar_.getByteString(index);
    }

    public static final int AMOUNT_FIELD_NUMBER = 5;
    private int amount_;
    /**
     * <pre>
     * 群人数
     * </pre>
     *
     * <code>int32 amount = 5;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int OWNER_FIELD_NUMBER = 6;
    private long owner_;
    /**
     * <pre>
     * 群主，只能为医联主库用户
     * </pre>
     *
     * <code>int64 owner = 6;</code>
     */
    public long getOwner() {
      return owner_;
    }

    public static final int BUSINESSTYPE_FIELD_NUMBER = 7;
    private int businessType_;
    /**
     * <pre>
     *  群业务类型  0：普通群 1：问诊
     * </pre>
     *
     * <code>int32 businessType = 7;</code>
     */
    public int getBusinessType() {
      return businessType_;
    }

    public static final int BUSINESSID_FIELD_NUMBER = 8;
    private long businessId_;
    /**
     * <pre>
     *  群业务id   如businessType！=0.则businessId 为具体业务业务id
     * </pre>
     *
     * <code>int64 businessId = 8;</code>
     */
    public long getBusinessId() {
      return businessId_;
    }

    public static final int AVATARURL_FIELD_NUMBER = 9;
    private volatile Object avatarUrl_;
    /**
     * <pre>
     *用户设置的头像
     * </pre>
     *
     * <code>string avatarUrl = 9;</code>
     */
    public String getAvatarUrl() {
      Object ref = avatarUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        avatarUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户设置的头像
     * </pre>
     *
     * <code>string avatarUrl = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarUrlBytes() {
      Object ref = avatarUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        avatarUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISPUBLIC_FIELD_NUMBER = 10;
    private int isPublic_;
    /**
     * <pre>
     * 是否公开群
     * </pre>
     *
     * <code>int32 isPublic = 10;</code>
     */
    public int getIsPublic() {
      return isPublic_;
    }

    public static final int ISFORBIDDEN_FIELD_NUMBER = 11;
    private int isForbidden_;
    /**
     * <pre>
     * 是否被屏蔽
     * </pre>
     *
     * <code>int32 isForbidden = 11;</code>
     */
    public int getIsForbidden() {
      return isForbidden_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      for (int i = 0; i < avatar_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, avatar_.getRaw(i));
      }
      if (amount_ != 0) {
        output.writeInt32(5, amount_);
      }
      if (owner_ != 0L) {
        output.writeInt64(6, owner_);
      }
      if (businessType_ != 0) {
        output.writeInt32(7, businessType_);
      }
      if (businessId_ != 0L) {
        output.writeInt64(8, businessId_);
      }
      if (!getAvatarUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, avatarUrl_);
      }
      if (isPublic_ != 0) {
        output.writeInt32(10, isPublic_);
      }
      if (isForbidden_ != 0) {
        output.writeInt32(11, isForbidden_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < avatar_.size(); i++) {
          dataSize += computeStringSizeNoTag(avatar_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAvatarList().size();
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, amount_);
      }
      if (owner_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, owner_);
      }
      if (businessType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, businessType_);
      }
      if (businessId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, businessId_);
      }
      if (!getAvatarUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, avatarUrl_);
      }
      if (isPublic_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, isPublic_);
      }
      if (isForbidden_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, isForbidden_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Group)) {
        return super.equals(obj);
      }
      Group other = (Group) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getAvatarList()
          .equals(other.getAvatarList());
      result = result && (getAmount()
          == other.getAmount());
      result = result && (getOwner()
          == other.getOwner());
      result = result && (getBusinessType()
          == other.getBusinessType());
      result = result && (getBusinessId()
          == other.getBusinessId());
      result = result && getAvatarUrl()
          .equals(other.getAvatarUrl());
      result = result && (getIsPublic()
          == other.getIsPublic());
      result = result && (getIsForbidden()
          == other.getIsForbidden());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getAvatarCount() > 0) {
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatarList().hashCode();
      }
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOwner());
      hash = (37 * hash) + BUSINESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessType();
      hash = (37 * hash) + BUSINESSID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBusinessId());
      hash = (37 * hash) + AVATARURL_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarUrl().hashCode();
      hash = (37 * hash) + ISPUBLIC_FIELD_NUMBER;
      hash = (53 * hash) + getIsPublic();
      hash = (37 * hash) + ISFORBIDDEN_FIELD_NUMBER;
      hash = (53 * hash) + getIsForbidden();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Group parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Group parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Group parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Group parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Group parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Group parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Group parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Group parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Group parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Group parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Group prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.medlinker.protocol.message.misc.Group}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.medlinker.protocol.message.misc.Group)
        GroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GroupOuterClass.internal_static_protocol_message_misc_Group_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GroupOuterClass.internal_static_protocol_message_misc_Group_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Group.class, Builder.class);
      }

      // Construct using com.medlinker.com.medlinker.protocol.message.misc.GroupOuterClass.Group.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        avatar_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0;

        owner_ = 0L;

        businessType_ = 0;

        businessId_ = 0L;

        avatarUrl_ = "";

        isPublic_ = 0;

        isForbidden_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GroupOuterClass.internal_static_protocol_message_misc_Group_descriptor;
      }

      public Group getDefaultInstanceForType() {
        return Group.getDefaultInstance();
      }

      public Group build() {
        Group result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Group buildPartial() {
        Group result = new Group(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          avatar_ = avatar_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.avatar_ = avatar_;
        result.amount_ = amount_;
        result.owner_ = owner_;
        result.businessType_ = businessType_;
        result.businessId_ = businessId_;
        result.avatarUrl_ = avatarUrl_;
        result.isPublic_ = isPublic_;
        result.isForbidden_ = isForbidden_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Group) {
          return mergeFrom((Group)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Group other) {
        if (other == Group.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.avatar_.isEmpty()) {
          if (avatar_.isEmpty()) {
            avatar_ = other.avatar_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAvatarIsMutable();
            avatar_.addAll(other.avatar_);
          }
          onChanged();
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (other.getOwner() != 0L) {
          setOwner(other.getOwner());
        }
        if (other.getBusinessType() != 0) {
          setBusinessType(other.getBusinessType());
        }
        if (other.getBusinessId() != 0L) {
          setBusinessId(other.getBusinessId());
        }
        if (!other.getAvatarUrl().isEmpty()) {
          avatarUrl_ = other.avatarUrl_;
          onChanged();
        }
        if (other.getIsPublic() != 0) {
          setIsPublic(other.getIsPublic());
        }
        if (other.getIsForbidden() != 0) {
          setIsForbidden(other.getIsForbidden());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Group parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Group) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList avatar_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAvatarIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          avatar_ = new com.google.protobuf.LazyStringArrayList(avatar_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAvatarList() {
        return avatar_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public int getAvatarCount() {
        return avatar_.size();
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public String getAvatar(int index) {
        return avatar_.get(index);
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes(int index) {
        return avatar_.getByteString(index);
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public Builder setAvatar(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAvatarIsMutable();
        avatar_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public Builder addAvatar(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAvatarIsMutable();
        avatar_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public Builder addAllAvatar(
          Iterable<String> values) {
        ensureAvatarIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, avatar_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public Builder clearAvatar() {
        avatar_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 很多个用户的头像
       * </pre>
       *
       * <code>repeated string avatar = 4;</code>
       */
      public Builder addAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAvatarIsMutable();
        avatar_.add(value);
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <pre>
       * 群人数
       * </pre>
       *
       * <code>int32 amount = 5;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * 群人数
       * </pre>
       *
       * <code>int32 amount = 5;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群人数
       * </pre>
       *
       * <code>int32 amount = 5;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private long owner_ ;
      /**
       * <pre>
       * 群主，只能为医联主库用户
       * </pre>
       *
       * <code>int64 owner = 6;</code>
       */
      public long getOwner() {
        return owner_;
      }
      /**
       * <pre>
       * 群主，只能为医联主库用户
       * </pre>
       *
       * <code>int64 owner = 6;</code>
       */
      public Builder setOwner(long value) {
        
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群主，只能为医联主库用户
       * </pre>
       *
       * <code>int64 owner = 6;</code>
       */
      public Builder clearOwner() {
        
        owner_ = 0L;
        onChanged();
        return this;
      }

      private int businessType_ ;
      /**
       * <pre>
       *  群业务类型  0：普通群 1：问诊
       * </pre>
       *
       * <code>int32 businessType = 7;</code>
       */
      public int getBusinessType() {
        return businessType_;
      }
      /**
       * <pre>
       *  群业务类型  0：普通群 1：问诊
       * </pre>
       *
       * <code>int32 businessType = 7;</code>
       */
      public Builder setBusinessType(int value) {
        
        businessType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  群业务类型  0：普通群 1：问诊
       * </pre>
       *
       * <code>int32 businessType = 7;</code>
       */
      public Builder clearBusinessType() {
        
        businessType_ = 0;
        onChanged();
        return this;
      }

      private long businessId_ ;
      /**
       * <pre>
       *  群业务id   如businessType！=0.则businessId 为具体业务业务id
       * </pre>
       *
       * <code>int64 businessId = 8;</code>
       */
      public long getBusinessId() {
        return businessId_;
      }
      /**
       * <pre>
       *  群业务id   如businessType！=0.则businessId 为具体业务业务id
       * </pre>
       *
       * <code>int64 businessId = 8;</code>
       */
      public Builder setBusinessId(long value) {
        
        businessId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  群业务id   如businessType！=0.则businessId 为具体业务业务id
       * </pre>
       *
       * <code>int64 businessId = 8;</code>
       */
      public Builder clearBusinessId() {
        
        businessId_ = 0L;
        onChanged();
        return this;
      }

      private Object avatarUrl_ = "";
      /**
       * <pre>
       *用户设置的头像
       * </pre>
       *
       * <code>string avatarUrl = 9;</code>
       */
      public String getAvatarUrl() {
        Object ref = avatarUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          avatarUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *用户设置的头像
       * </pre>
       *
       * <code>string avatarUrl = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarUrlBytes() {
        Object ref = avatarUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          avatarUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户设置的头像
       * </pre>
       *
       * <code>string avatarUrl = 9;</code>
       */
      public Builder setAvatarUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatarUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户设置的头像
       * </pre>
       *
       * <code>string avatarUrl = 9;</code>
       */
      public Builder clearAvatarUrl() {
        
        avatarUrl_ = getDefaultInstance().getAvatarUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户设置的头像
       * </pre>
       *
       * <code>string avatarUrl = 9;</code>
       */
      public Builder setAvatarUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatarUrl_ = value;
        onChanged();
        return this;
      }

      private int isPublic_ ;
      /**
       * <pre>
       * 是否公开群
       * </pre>
       *
       * <code>int32 isPublic = 10;</code>
       */
      public int getIsPublic() {
        return isPublic_;
      }
      /**
       * <pre>
       * 是否公开群
       * </pre>
       *
       * <code>int32 isPublic = 10;</code>
       */
      public Builder setIsPublic(int value) {
        
        isPublic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否公开群
       * </pre>
       *
       * <code>int32 isPublic = 10;</code>
       */
      public Builder clearIsPublic() {
        
        isPublic_ = 0;
        onChanged();
        return this;
      }

      private int isForbidden_ ;
      /**
       * <pre>
       * 是否被屏蔽
       * </pre>
       *
       * <code>int32 isForbidden = 11;</code>
       */
      public int getIsForbidden() {
        return isForbidden_;
      }
      /**
       * <pre>
       * 是否被屏蔽
       * </pre>
       *
       * <code>int32 isForbidden = 11;</code>
       */
      public Builder setIsForbidden(int value) {
        
        isForbidden_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否被屏蔽
       * </pre>
       *
       * <code>int32 isForbidden = 11;</code>
       */
      public Builder clearIsForbidden() {
        
        isForbidden_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.medlinker.protocol.message.misc.Group)
    }

    // @@protoc_insertion_point(class_scope:com.medlinker.protocol.message.misc.Group)
    private static final Group DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Group();
    }

    public static Group getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Group>
        PARSER = new com.google.protobuf.AbstractParser<Group>() {
      public Group parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Group(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Group> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Group> getParserForType() {
      return PARSER;
    }

    public Group getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_message_misc_Group_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_message_misc_Group_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020misc/group.proto\022\025protocol.message.mis" +
      "c\"\264\001\n\005Group\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\003 \001(\t\022\016\n" +
      "\006avatar\030\004 \003(\t\022\016\n\006amount\030\005 \001(\005\022\r\n\005owner\030\006" +
      " \001(\003\022\024\n\014businessType\030\007 \001(\005\022\022\n\nbusinessId" +
      "\030\010 \001(\003\022\021\n\tavatarUrl\030\t \001(\t\022\020\n\010isPublic\030\n " +
      "\001(\005\022\023\n\013isForbidden\030\013 \001(\005BB\n#com.medlinke" +
      "r.com.medlinker.protocol.message.miscZ\033grape/protocol/" +
      "message/miscb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_message_misc_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_message_misc_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_message_misc_Group_descriptor,
        new String[] { "Id", "Name", "Avatar", "Amount", "Owner", "BusinessType", "BusinessId", "AvatarUrl", "IsPublic", "IsForbidden", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
